USE Music;
GO

CREATE TABLE VERSION_TABLE(
    version int,
    PRIMARY KEY(version)
);
INSERT INTO VERSION_TABLE VALUES(0);

CREATE TABLE PROCEDURES_TABLE(
	fromVersion INT,
	toVersion INT,
	nameProc VARCHAR(255),
	PRIMARY KEY(fromVersion, toVersion)
);

INSERT INTO PROCEDURES_TABLE VALUES(0, 1, 'changeTypeOfGenreNameTypeChar');
INSERT INTO PROCEDURES_TABLE VALUES(1, 2, 'addPriceToSubscription');
INSERT INTO PROCEDURES_TABLE VALUES(2, 3, 'addDefaultPlanDesc');
INSERT INTO PROCEDURES_TABLE VALUES(3, 4, 'createSongAwards');
INSERT INTO PROCEDURES_TABLE VALUES(4, 5, 'addPrimaryKey');
INSERT INTO PROCEDURES_TABLE VALUES(5, 6, 'addCandidateSubscription');
INSERT INTO PROCEDURES_TABLE VALUES(6, 7, 'addForeignKey');
INSERT INTO PROCEDURES_TABLE VALUES(7, 6, 'removeForeignKey');
INSERT INTO PROCEDURES_TABLE VALUES(6, 5, 'removeCandidateSubscription');
INSERT INTO PROCEDURES_TABLE VALUES(5, 4, 'removePrimaryKey');
INSERT INTO PROCEDURES_TABLE VALUES(4, 3, 'dropSongAwards');
INSERT INTO PROCEDURES_TABLE VALUES(3, 2, 'removeDefaultPlanDesc');
INSERT INTO PROCEDURES_TABLE VALUES(2, 1, 'removePriceFromSubscription');
INSERT INTO PROCEDURES_TABLE VALUES(1, 0, 'changeTypeOfGenreNameTypeVarchar');
